<<<<<<< HEAD
// 曹帅(2305000119)成绩同步数据
var SYNC_GRADES_DATA = [
  {
    "courseId": "4140800BL",
    "courseName": "大学生心理健康教育",
    "code": "4140800BL",
    "name": "大学生心理健康教育",
    "credit": 2.0,
    "credits": 2.0,
    "score": 60,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "health"
  },
  {
    "courseId": "1130110EZ",
    "courseName": "体育III",
    "code": "1130110EZ",
    "name": "体育III",
    "credit": 1.0,
    "credits": 1.0,
    "score": 64.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策I",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 86.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "1144200AZ",
    "courseName": "大学生职业发展与创业就业指导II",
    "code": "1144200AZ",
    "name": "大学生职业发展与创业就业指导",
    "credit": 0.5,
    "credits": 0.5,
    "score": 85.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "innovation"
  },
  {
    "courseId": "1060110GL",
    "courseName": "高等数学I",
    "code": "1060110GL",
    "name": "高等数学I",
    "credit": 3.0,
    "credits": 3.0,
    "score": 80.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "2021210BL",
    "courseName": "药事管理学",
    "code": "2021210BL",
    "name": "药事管理学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 81.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1070110EZ",
    "courseName": "大学英语I",
    "code": "1070110EZ",
    "name": "大学英语I",
    "credit": 2.5,
    "credits": 2.5,
    "score": 72.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "2021810BL",
    "courseName": "管理学",
    "code": "2021810BL",
    "name": "管理学",
    "credit": 2.5,
    "credits": 2.5,
    "score": 80.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "P_大学计算机基",
    "courseName": "大学计算机基础",
    "code": "P_大学计算机基",
    "name": "大学计算机基础",
    "credit": 1.0,
    "credits": 1.0,
    "score": 75.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "2022910AS",
    "courseName": "会计学实验",
    "code": "2022910AS",
    "name": "会计学实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 89.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "P_大学计算机基",
    "courseName": "大学计算机基础实验",
    "code": "P_大学计算机基",
    "name": "大学计算机基础实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 87.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "2022910CL",
    "courseName": "会计学",
    "code": "2022910CL",
    "name": "会计学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 92.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1130110BZ",
    "courseName": "体育I",
    "code": "1130110BZ",
    "name": "体育I",
    "credit": 1.0,
    "credits": 1.0,
    "score": 71.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "2024010BL",
    "courseName": "市场营销学",
    "code": "2024010BL",
    "name": "市场营销学",
    "credit": 2.5,
    "credits": 2.5,
    "score": 86.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1140210BS",
    "courseName": "军事技能训练",
    "code": "1140210BS",
    "name": "军事技能训练",
    "credit": 1.5,
    "credits": 1.5,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "practice",
    "module": "mil_train"
  },
  {
    "courseId": "1073210BL",
    "courseName": "大学英语翻译与写作",
    "code": "1073210BL",
    "name": "大学英语翻译与写作",
    "credit": 1.5,
    "credits": 1.5,
    "score": 70.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "1144200AZ",
    "courseName": "大学生职业发展与创业就业指导I",
    "code": "1144200AZ",
    "name": "大学生职业发展与创业就业指导",
    "credit": 0.5,
    "credits": 0.5,
    "score": 80,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "innovation"
  },
  {
    "courseId": "4020800AL",
    "courseName": "药物经济学",
    "code": "4020800AL",
    "name": "药物经济学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "2032710AL",
    "courseName": "大学化学I",
    "code": "2032710AL",
    "name": "大学化学I",
    "credit": 2.5,
    "credits": 2.5,
    "score": 60,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "4027710AL",
    "courseName": "国际商务",
    "code": "4027710AL",
    "name": "国际商务",
    "credit": 2.5,
    "credits": 2.5,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "4027810CL",
    "courseName": "经济学",
    "code": "4027810CL",
    "name": "经济学",
    "credit": 4.0,
    "credits": 4.0,
    "score": 63.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "2032710AS",
    "courseName": "大学化学实验I",
    "code": "2032710AS",
    "name": "大学化学实验I",
    "credit": 1.5,
    "credits": 1.5,
    "score": 80,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "4060300DL",
    "courseName": "线性代数",
    "code": "4060300DL",
    "name": "线性代数",
    "credit": 2.0,
    "credits": 2.0,
    "score": 70.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "P_创业法学",
    "courseName": "创业法学",
    "code": "P_创业法学",
    "name": "创业法学",
    "credit": 1.0,
    "credits": 1.0,
    "score": 98.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "P_现代物理学发",
    "courseName": "现代物理学发展史",
    "code": "P_现代物理学发",
    "name": "现代物理学发展史",
    "credit": 1.0,
    "credits": 1.0,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "4144400BL",
    "courseName": "音乐鉴赏",
    "code": "4144400BL",
    "name": "音乐鉴赏",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "art"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策IV",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 88.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_党史",
    "courseName": "党史",
    "code": "P_党史",
    "name": "党史",
    "credit": 1.0,
    "credits": 1.0,
    "score": 91.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "1062110AL",
    "courseName": "大学数学进阶",
    "code": "1062110AL",
    "name": "大学数学进阶",
    "credit": 2.0,
    "credits": 2.0,
    "score": 97.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "PRACTICE_LABOR",
    "courseName": "劳动I",
    "code": "PRACTICE_LABOR",
    "name": "劳动",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "practice",
    "module": "labor"
  },
  {
    "courseId": "1130110FZ",
    "courseName": "体育IV",
    "code": "1130110FZ",
    "name": "体育IV",
    "credit": 1.0,
    "credits": 1.0,
    "score": 70.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "1010110AS05",
    "courseName": "思想政治理论实践课（思想道德与法治）",
    "code": "1010110AS05",
    "name": "思想政治理论实践课（思想道德与法治）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 93.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2027310AS",
    "courseName": "应用统计学实验",
    "code": "2027310AS",
    "name": "应用统计学实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 96.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1010410CL",
    "courseName": "思想道德与法治",
    "code": "1010410CL",
    "name": "思想道德与法治",
    "credit": 2.5,
    "credits": 2.5,
    "score": 91.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2027310BL",
    "courseName": "应用统计学",
    "code": "2027310BL",
    "name": "应用统计学",
    "credit": 1.5,
    "credits": 1.5,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1010110AS03",
    "courseName": "思想政治理论实践课（中国近现代史纲要）",
    "code": "1010110AS03",
    "name": "思想政治理论实践课（中国近现代史纲要）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 70.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "3022310BL",
    "courseName": "财务管理",
    "code": "3022310BL",
    "name": "财务管理",
    "credit": 1.5,
    "credits": 1.5,
    "score": 84.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1010210CL",
    "courseName": "中国近现代史纲要",
    "code": "1010210CL",
    "name": "中国近现代史纲要",
    "credit": 2.5,
    "credits": 2.5,
    "score": 69.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "3021000CL",
    "courseName": "组织行为学",
    "code": "3021000CL",
    "name": "组织行为学",
    "credit": 1.0,
    "credits": 1.0,
    "score": 95.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策II",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 84.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "PRACTICE_LABOR",
    "courseName": "特色劳动",
    "code": "PRACTICE_LABOR",
    "name": "劳动",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "practice",
    "module": "labor"
  },
  {
    "courseId": "1060100DL",
    "courseName": "高等数学II",
    "code": "1060100DL",
    "name": "高等数学II",
    "credit": 3.0,
    "credits": 3.0,
    "score": 67.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "4020400AL",
    "courseName": "博弈论",
    "code": "4020400AL",
    "name": "博弈论",
    "credit": 2.0,
    "credits": 2.0,
    "score": 87.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1060200CL",
    "courseName": "概率论与数理统计",
    "code": "1060200CL",
    "name": "概率论与数理统计",
    "credit": 2.0,
    "credits": 2.0,
    "score": 64.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "4023010CL",
    "courseName": "运筹学",
    "code": "4023010CL",
    "name": "运筹学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 67.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "P_计算机程序设",
    "courseName": "计算机程序设计（Python）",
    "code": "P_计算机程序设",
    "name": "计算机程序设计（Python）",
    "credit": 2.0,
    "credits": 2.0,
    "score": 75.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "4028210AL",
    "courseName": "管理心理学",
    "code": "4028210AL",
    "name": "管理心理学",
    "credit": 2.5,
    "credits": 2.5,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "1130110DZ",
    "courseName": "体育II",
    "code": "1130110DZ",
    "name": "体育II",
    "credit": 1.0,
    "credits": 1.0,
    "score": 64.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "P_习近平法治思",
    "courseName": "习近平法治思想",
    "code": "P_习近平法治思",
    "name": "习近平法治思想",
    "credit": 1.0,
    "credits": 1.0,
    "score": 80,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1140100AL",
    "courseName": "军事理论",
    "code": "1140100AL",
    "name": "军事理论",
    "credit": 1.5,
    "credits": 1.5,
    "score": 77.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "P_英语报刊选读",
    "courseName": "英语报刊选读",
    "code": "P_英语报刊选读",
    "name": "英语报刊选读",
    "credit": 1.5,
    "credits": 1.5,
    "score": 73.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "P_计算机程序设",
    "courseName": "计算机程序设计（Python）实验",
    "code": "P_计算机程序设",
    "name": "计算机程序设计（Python）实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 88.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "1010110AS04",
    "courseName": "思想政治理论实践课（毛泽东思想和中国特色社会主义理论体系概论）",
    "code": "1010110AS04",
    "name": "思想政治理论实践课（毛泽东思想和中国特色社会主义理论体系概论）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2032710BL",
    "courseName": "大学化学II",
    "code": "2032710BL",
    "name": "大学化学II",
    "credit": 3.0,
    "credits": 3.0,
    "score": 69.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1010310DL",
    "courseName": "毛泽东思想和中国特色社会主义理论体系概论",
    "code": "1010310DL",
    "name": "毛泽东思想和中国特色社会主义理论体系概论",
    "credit": 2.5,
    "credits": 2.5,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2032710BS",
    "courseName": "大学化学实验II",
    "code": "2032710BS",
    "name": "大学化学实验II",
    "credit": 1.0,
    "credits": 1.0,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "5016410BL",
    "courseName": "习近平新时代中国特色社会主义思想概论",
    "code": "5016410BL",
    "name": "习近平新时代中国特色社会主义思想概论",
    "credit": 3.0,
    "credits": 3.0,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_劳动通论",
    "courseName": "劳动通论",
    "code": "P_劳动通论",
    "name": "劳动通论",
    "credit": 2.0,
    "credits": 2.0,
    "score": 97.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策V",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_医药伦理学",
    "courseName": "医药伦理学",
    "code": "P_医药伦理学",
    "name": "医药伦理学",
    "credit": 1.0,
    "credits": 1.0,
    "score": 90,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "1016210AL",
    "courseName": "创业学",
    "code": "1016210AL",
    "name": "创业学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 89.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "P_戏曲鉴赏",
    "courseName": "戏曲鉴赏",
    "code": "P_戏曲鉴赏",
    "name": "戏曲鉴赏",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "art"
  },
  {
    "courseId": "2022510CL",
    "courseName": "经济法",
    "code": "2022510CL",
    "name": "经济法",
    "credit": 2.0,
    "credits": 2.0,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "PRACTICE_LABOR",
    "courseName": "劳动II",
    "code": "PRACTICE_LABOR",
    "name": "劳动",
    "credit": 1.0,
    "credits": 1.0,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "practice",
    "module": "labor"
  },
  {
    "courseId": "P_中国古代小说",
    "courseName": "中国古代小说巅峰-四大名著鉴赏",
    "code": "P_中国古代小说",
    "name": "中国古代小说巅峰-四大名著鉴赏",
    "credit": 2.0,
    "credits": 2.0,
    "score": 99.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1070100DZ",
    "courseName": "大学英语II",
    "code": "1070100DZ",
    "name": "大学英语II",
    "credit": 3.5,
    "credits": 3.5,
    "score": 79.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "4020500AL",
    "courseName": "技术经济学",
    "code": "4020500AL",
    "name": "技术经济学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 63.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1073100BL",
    "courseName": "应用写作",
    "code": "1073100BL",
    "name": "应用写作",
    "credit": 1.0,
    "credits": 1.0,
    "score": 84.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "4023710AL",
    "courseName": "医药电子商务",
    "code": "4023710AL",
    "name": "医药电子商务",
    "credit": 2.0,
    "credits": 2.0,
    "score": 84.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "4010600CL",
    "courseName": "中华优秀传统文化",
    "code": "4010600CL",
    "name": "中华优秀传统文化",
    "credit": 1.0,
    "credits": 1.0,
    "score": 85.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "4024100AL",
    "courseName": "医药消费行为学",
    "code": "4024100AL",
    "name": "医药消费行为学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 78.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "P_演讲与口才",
    "courseName": "演讲与口才",
    "code": "P_演讲与口才",
    "name": "演讲与口才",
    "credit": 1.0,
    "credits": 1.0,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "4025810BL",
    "courseName": "人力资源管理",
    "code": "4025810BL",
    "name": "人力资源管理",
    "credit": 1.0,
    "credits": 1.0,
    "score": 86.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1010110AS02",
    "courseName": "思想政治理论实践课（马克思主义基本原理）",
    "code": "1010110AS02",
    "name": "思想政治理论实践课（马克思主义基本原理）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 94.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "4026910BL",
    "courseName": "国际经济合作",
    "code": "4026910BL",
    "name": "国际经济合作",
    "credit": 2.0,
    "credits": 2.0,
    "score": 91.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "1010110BL",
    "courseName": "马克思主义基本原理",
    "code": "1010110BL",
    "name": "马克思主义基本原理",
    "credit": 2.5,
    "credits": 2.5,
    "score": 85.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_创新中国",
    "courseName": "创新中国",
    "code": "P_创新中国",
    "name": "创新中国",
    "credit": 1.0,
    "credits": 1.0,
    "score": 98.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策III",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 79.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "4028510CL",
    "courseName": "公司治理",
    "code": "4028510CL",
    "name": "公司治理",
    "credit": 1.5,
    "credits": 1.5,
    "score": 94.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_req"
  }
];
=======
// 曹帅(2305000119)成绩同步数据
var SYNC_GRADES_DATA = [
  {
    "courseId": "4140800BL",
    "courseName": "大学生心理健康教育",
    "code": "4140800BL",
    "name": "大学生心理健康教育",
    "credit": 2.0,
    "credits": 2.0,
    "score": 60,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "health"
  },
  {
    "courseId": "1130110EZ",
    "courseName": "体育III",
    "code": "1130110EZ",
    "name": "体育III",
    "credit": 1.0,
    "credits": 1.0,
    "score": 64.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策I",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 86.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "1144200AZ",
    "courseName": "大学生职业发展与创业就业指导II",
    "code": "1144200AZ",
    "name": "大学生职业发展与创业就业指导",
    "credit": 0.5,
    "credits": 0.5,
    "score": 85.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "innovation"
  },
  {
    "courseId": "1060110GL",
    "courseName": "高等数学I",
    "code": "1060110GL",
    "name": "高等数学I",
    "credit": 3.0,
    "credits": 3.0,
    "score": 80.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "2021210BL",
    "courseName": "药事管理学",
    "code": "2021210BL",
    "name": "药事管理学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 81.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1070110EZ",
    "courseName": "大学英语I",
    "code": "1070110EZ",
    "name": "大学英语I",
    "credit": 2.5,
    "credits": 2.5,
    "score": 72.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "2021810BL",
    "courseName": "管理学",
    "code": "2021810BL",
    "name": "管理学",
    "credit": 2.5,
    "credits": 2.5,
    "score": 80.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "P_大学计算机基",
    "courseName": "大学计算机基础",
    "code": "P_大学计算机基",
    "name": "大学计算机基础",
    "credit": 1.0,
    "credits": 1.0,
    "score": 75.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "2022910AS",
    "courseName": "会计学实验",
    "code": "2022910AS",
    "name": "会计学实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 89.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "P_大学计算机基",
    "courseName": "大学计算机基础实验",
    "code": "P_大学计算机基",
    "name": "大学计算机基础实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 87.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "2022910CL",
    "courseName": "会计学",
    "code": "2022910CL",
    "name": "会计学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 92.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1130110BZ",
    "courseName": "体育I",
    "code": "1130110BZ",
    "name": "体育I",
    "credit": 1.0,
    "credits": 1.0,
    "score": 71.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "2024010BL",
    "courseName": "市场营销学",
    "code": "2024010BL",
    "name": "市场营销学",
    "credit": 2.5,
    "credits": 2.5,
    "score": 86.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1140210BS",
    "courseName": "军事技能训练",
    "code": "1140210BS",
    "name": "军事技能训练",
    "credit": 1.5,
    "credits": 1.5,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "practice",
    "module": "mil_train"
  },
  {
    "courseId": "1073210BL",
    "courseName": "大学英语翻译与写作",
    "code": "1073210BL",
    "name": "大学英语翻译与写作",
    "credit": 1.5,
    "credits": 1.5,
    "score": 70.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "1144200AZ",
    "courseName": "大学生职业发展与创业就业指导I",
    "code": "1144200AZ",
    "name": "大学生职业发展与创业就业指导",
    "credit": 0.5,
    "credits": 0.5,
    "score": 80,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "innovation"
  },
  {
    "courseId": "4020800AL",
    "courseName": "药物经济学",
    "code": "4020800AL",
    "name": "药物经济学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "2032710AL",
    "courseName": "大学化学I",
    "code": "2032710AL",
    "name": "大学化学I",
    "credit": 2.5,
    "credits": 2.5,
    "score": 60,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "4027710AL",
    "courseName": "国际商务",
    "code": "4027710AL",
    "name": "国际商务",
    "credit": 2.5,
    "credits": 2.5,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "4027810CL",
    "courseName": "经济学",
    "code": "4027810CL",
    "name": "经济学",
    "credit": 4.0,
    "credits": 4.0,
    "score": 63.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "2032710AS",
    "courseName": "大学化学实验I",
    "code": "2032710AS",
    "name": "大学化学实验I",
    "credit": 1.5,
    "credits": 1.5,
    "score": 80,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "4060300DL",
    "courseName": "线性代数",
    "code": "4060300DL",
    "name": "线性代数",
    "credit": 2.0,
    "credits": 2.0,
    "score": 70.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "P_创业法学",
    "courseName": "创业法学",
    "code": "P_创业法学",
    "name": "创业法学",
    "credit": 1.0,
    "credits": 1.0,
    "score": 98.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "P_现代物理学发",
    "courseName": "现代物理学发展史",
    "code": "P_现代物理学发",
    "name": "现代物理学发展史",
    "credit": 1.0,
    "credits": 1.0,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 3,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "4144400BL",
    "courseName": "音乐鉴赏",
    "code": "4144400BL",
    "name": "音乐鉴赏",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "art"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策IV",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 88.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_党史",
    "courseName": "党史",
    "code": "P_党史",
    "name": "党史",
    "credit": 1.0,
    "credits": 1.0,
    "score": 91.0,
    "required": false,
    "category": "选修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "1062110AL",
    "courseName": "大学数学进阶",
    "code": "1062110AL",
    "name": "大学数学进阶",
    "credit": 2.0,
    "credits": 2.0,
    "score": 97.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "PRACTICE_LABOR",
    "courseName": "劳动I",
    "code": "PRACTICE_LABOR",
    "name": "劳动",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "practice",
    "module": "labor"
  },
  {
    "courseId": "1130110FZ",
    "courseName": "体育IV",
    "code": "1130110FZ",
    "name": "体育IV",
    "credit": 1.0,
    "credits": 1.0,
    "score": 70.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "1010110AS05",
    "courseName": "思想政治理论实践课（思想道德与法治）",
    "code": "1010110AS05",
    "name": "思想政治理论实践课（思想道德与法治）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 93.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2027310AS",
    "courseName": "应用统计学实验",
    "code": "2027310AS",
    "name": "应用统计学实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 96.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1010410CL",
    "courseName": "思想道德与法治",
    "code": "1010410CL",
    "name": "思想道德与法治",
    "credit": 2.5,
    "credits": 2.5,
    "score": 91.0,
    "required": true,
    "category": "必修",
    "semester": 1,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2027310BL",
    "courseName": "应用统计学",
    "code": "2027310BL",
    "name": "应用统计学",
    "credit": 1.5,
    "credits": 1.5,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1010110AS03",
    "courseName": "思想政治理论实践课（中国近现代史纲要）",
    "code": "1010110AS03",
    "name": "思想政治理论实践课（中国近现代史纲要）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 70.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "3022310BL",
    "courseName": "财务管理",
    "code": "3022310BL",
    "name": "财务管理",
    "credit": 1.5,
    "credits": 1.5,
    "score": 84.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1010210CL",
    "courseName": "中国近现代史纲要",
    "code": "1010210CL",
    "name": "中国近现代史纲要",
    "credit": 2.5,
    "credits": 2.5,
    "score": 69.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "3021000CL",
    "courseName": "组织行为学",
    "code": "3021000CL",
    "name": "组织行为学",
    "credit": 1.0,
    "credits": 1.0,
    "score": 95.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策II",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 84.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "PRACTICE_LABOR",
    "courseName": "特色劳动",
    "code": "PRACTICE_LABOR",
    "name": "劳动",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "practice",
    "module": "labor"
  },
  {
    "courseId": "1060100DL",
    "courseName": "高等数学II",
    "code": "1060100DL",
    "name": "高等数学II",
    "credit": 3.0,
    "credits": 3.0,
    "score": 67.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "4020400AL",
    "courseName": "博弈论",
    "code": "4020400AL",
    "name": "博弈论",
    "credit": 2.0,
    "credits": 2.0,
    "score": 87.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1060200CL",
    "courseName": "概率论与数理统计",
    "code": "1060200CL",
    "name": "概率论与数理统计",
    "credit": 2.0,
    "credits": 2.0,
    "score": 64.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "math"
  },
  {
    "courseId": "4023010CL",
    "courseName": "运筹学",
    "code": "4023010CL",
    "name": "运筹学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 67.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "P_计算机程序设",
    "courseName": "计算机程序设计（Python）",
    "code": "P_计算机程序设",
    "name": "计算机程序设计（Python）",
    "credit": 2.0,
    "credits": 2.0,
    "score": 75.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "4028210AL",
    "courseName": "管理心理学",
    "code": "4028210AL",
    "name": "管理心理学",
    "credit": 2.5,
    "credits": 2.5,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "1130110DZ",
    "courseName": "体育II",
    "code": "1130110DZ",
    "name": "体育II",
    "credit": 1.0,
    "credits": 1.0,
    "score": 64.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "P_习近平法治思",
    "courseName": "习近平法治思想",
    "code": "P_习近平法治思",
    "name": "习近平法治思想",
    "credit": 1.0,
    "credits": 1.0,
    "score": 80,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1140100AL",
    "courseName": "军事理论",
    "code": "1140100AL",
    "name": "军事理论",
    "credit": 1.5,
    "credits": 1.5,
    "score": 77.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "military_pe"
  },
  {
    "courseId": "P_英语报刊选读",
    "courseName": "英语报刊选读",
    "code": "P_英语报刊选读",
    "name": "英语报刊选读",
    "credit": 1.5,
    "credits": 1.5,
    "score": 73.0,
    "required": false,
    "category": "选修",
    "semester": 4,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "P_计算机程序设",
    "courseName": "计算机程序设计（Python）实验",
    "code": "P_计算机程序设",
    "name": "计算机程序设计（Python）实验",
    "credit": 0.5,
    "credits": 0.5,
    "score": 88.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "computer"
  },
  {
    "courseId": "1010110AS04",
    "courseName": "思想政治理论实践课（毛泽东思想和中国特色社会主义理论体系概论）",
    "code": "1010110AS04",
    "name": "思想政治理论实践课（毛泽东思想和中国特色社会主义理论体系概论）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2032710BL",
    "courseName": "大学化学II",
    "code": "2032710BL",
    "name": "大学化学II",
    "credit": 3.0,
    "credits": 3.0,
    "score": 69.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1010310DL",
    "courseName": "毛泽东思想和中国特色社会主义理论体系概论",
    "code": "1010310DL",
    "name": "毛泽东思想和中国特色社会主义理论体系概论",
    "credit": 2.5,
    "credits": 2.5,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 4,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "2032710BS",
    "courseName": "大学化学实验II",
    "code": "2032710BS",
    "name": "大学化学实验II",
    "credit": 1.0,
    "credits": 1.0,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "5016410BL",
    "courseName": "习近平新时代中国特色社会主义思想概论",
    "code": "5016410BL",
    "name": "习近平新时代中国特色社会主义思想概论",
    "credit": 3.0,
    "credits": 3.0,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_劳动通论",
    "courseName": "劳动通论",
    "code": "P_劳动通论",
    "name": "劳动通论",
    "credit": 2.0,
    "credits": 2.0,
    "score": 97.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策V",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 90.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_医药伦理学",
    "courseName": "医药伦理学",
    "code": "P_医药伦理学",
    "name": "医药伦理学",
    "credit": 1.0,
    "credits": 1.0,
    "score": 90,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "1016210AL",
    "courseName": "创业学",
    "code": "1016210AL",
    "name": "创业学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 89.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "P_戏曲鉴赏",
    "courseName": "戏曲鉴赏",
    "code": "P_戏曲鉴赏",
    "name": "戏曲鉴赏",
    "credit": 0.5,
    "credits": 0.5,
    "score": 90,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "art"
  },
  {
    "courseId": "2022510CL",
    "courseName": "经济法",
    "code": "2022510CL",
    "name": "经济法",
    "credit": 2.0,
    "credits": 2.0,
    "score": 87.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "PRACTICE_LABOR",
    "courseName": "劳动II",
    "code": "PRACTICE_LABOR",
    "name": "劳动",
    "credit": 1.0,
    "credits": 1.0,
    "score": 90,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "practice",
    "module": "labor"
  },
  {
    "courseId": "P_中国古代小说",
    "courseName": "中国古代小说巅峰-四大名著鉴赏",
    "code": "P_中国古代小说",
    "name": "中国古代小说巅峰-四大名著鉴赏",
    "credit": 2.0,
    "credits": 2.0,
    "score": 99.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1070100DZ",
    "courseName": "大学英语II",
    "code": "1070100DZ",
    "name": "大学英语II",
    "credit": 3.5,
    "credits": 3.5,
    "score": 79.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "foreign"
  },
  {
    "courseId": "4020500AL",
    "courseName": "技术经济学",
    "code": "4020500AL",
    "name": "技术经济学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 63.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "foundation",
    "module": "discipline"
  },
  {
    "courseId": "1073100BL",
    "courseName": "应用写作",
    "code": "1073100BL",
    "name": "应用写作",
    "credit": 1.0,
    "credits": 1.0,
    "score": 84.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "4023710AL",
    "courseName": "医药电子商务",
    "code": "4023710AL",
    "name": "医药电子商务",
    "credit": 2.0,
    "credits": 2.0,
    "score": 84.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "4010600CL",
    "courseName": "中华优秀传统文化",
    "code": "4010600CL",
    "name": "中华优秀传统文化",
    "credit": 1.0,
    "credits": 1.0,
    "score": 85.0,
    "required": true,
    "category": "必修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "4024100AL",
    "courseName": "医药消费行为学",
    "code": "4024100AL",
    "name": "医药消费行为学",
    "credit": 2.0,
    "credits": 2.0,
    "score": 78.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "P_演讲与口才",
    "courseName": "演讲与口才",
    "code": "P_演讲与口才",
    "name": "演讲与口才",
    "credit": 1.0,
    "credits": 1.0,
    "score": 86.0,
    "required": false,
    "category": "选修",
    "semester": 2,
    "platform": "general",
    "module": "humanities"
  },
  {
    "courseId": "4025810BL",
    "courseName": "人力资源管理",
    "code": "4025810BL",
    "name": "人力资源管理",
    "credit": 1.0,
    "credits": 1.0,
    "score": 86.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_req"
  },
  {
    "courseId": "1010110AS02",
    "courseName": "思想政治理论实践课（马克思主义基本原理）",
    "code": "1010110AS02",
    "name": "思想政治理论实践课（马克思主义基本原理）",
    "credit": 0.5,
    "credits": 0.5,
    "score": 94.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "4026910BL",
    "courseName": "国际经济合作",
    "code": "4026910BL",
    "name": "国际经济合作",
    "credit": 2.0,
    "credits": 2.0,
    "score": 91.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_elec"
  },
  {
    "courseId": "1010110BL",
    "courseName": "马克思主义基本原理",
    "code": "1010110BL",
    "name": "马克思主义基本原理",
    "credit": 2.5,
    "credits": 2.5,
    "score": 85.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "P_创新中国",
    "courseName": "创新中国",
    "code": "P_创新中国",
    "name": "创新中国",
    "credit": 1.0,
    "credits": 1.0,
    "score": 98.0,
    "required": false,
    "category": "选修",
    "semester": 5,
    "platform": "personal",
    "module": "free_elec"
  },
  {
    "courseId": "1014200AL",
    "courseName": "形势与政策III",
    "code": "1014200AL",
    "name": "形势与政策",
    "credit": 0.25,
    "credits": 0.25,
    "score": 79.0,
    "required": true,
    "category": "必修",
    "semester": 3,
    "platform": "general",
    "module": "sizheng"
  },
  {
    "courseId": "4028510CL",
    "courseName": "公司治理",
    "code": "4028510CL",
    "name": "公司治理",
    "credit": 1.5,
    "credits": 1.5,
    "score": 94.0,
    "required": true,
    "category": "必修",
    "semester": 5,
    "platform": "professional",
    "module": "prof_req"
  }
];
>>>>>>> origin/master
